name: pre-make_image

on:
  pull_request:

jobs:
  pre-make_image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker/setup-buildx-action@v3.9.0
      - uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: PUSH=1 make image-ui
